# Site settings
name: Yin Fan
email: yinfan519@gmail.com
author: Yin Fan
url: 
resume_site: 
github: https://github.com/YinFFF
linkedin: https://www.linkedin.com/in/yinfan519/
#baseurl: "/LessOrMore"
description: fan
meta_description: meta_description
motto: motto
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

#github_username: luoyan35714
highlighter: rouge

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_prefix: "ref-"

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

gems: [jekyll-paginate]

host: 10.0.0.9
port: 80

#FB:
#  comments :
#    provider : duoshuo
#    duoshuo:
#        short_name : luoyan35714
#    disqus :
#        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light

